In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import shap
import joblib

from sklearn.metrics import *
import matplotlib.pyplot as plt
from sklearn.linear_model import Lasso
from sklearn.inspection import permutation_importance

from sklearn.model_selection import train_test_split
from sklearn.feature_selection import f_regression, chi2
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler,
    RobustScaler,
    MinMaxScaler,
    OrdinalEncoder,
    TargetEncoder,
    FunctionTransformer,
)

sklearn.set_config(transform_output="pandas")

from sklearn.ensemble import RandomForestRegressor

from catboost import CatBoostRegressor

import lightgbm as lgb

import xgboost as xgb

from sklearn.model_selection import GridSearchCV, KFold, StratifiedKFold

# for model learning
from sklearn.model_selection import (
    train_test_split,
    RandomizedSearchCV,
    cross_val_score,
)

# tunning hyperparamters model
import optuna

In [37]:
test = pd.read_csv("test.csv")

In [53]:
one_row = pd.DataFrame(test.iloc[45, :].copy()).T
# one_row = test.iloc[60, :].copy()
one_row

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
45,1506,20,RL,NaN,10456,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal

In [52]:
one_row.to_csv("one_row.csv", index=False)

In [40]:
ten_rows = test.iloc[45:55, :].copy()
ten_rows

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
45,1506,20,RL,NaN,10456,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
46,1507,60,RL,80.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,WD,Normal
47,1508,50,RL,NaN,18837,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
48,1509,60,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdWo,NaN,0,6,2010,WD,Normal
49,1510,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
50,1511,20,RL,90.0,9900,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,ConLD,Normal
51,1512,20,RL,88.0,9680,Pave,NaN,Reg,Lvl,AllPub,...,204,0,NaN,GdPrv,NaN,0,4,2010,WD,Normal
52,1513,80,RL,NaN,10600,Pave,Pave,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,COD,Family
53,1514,90,RL,98.0,13260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,Oth,Abnorml
54,1515,50,RL,68.0,9724,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdWo,NaN,0,3,2010,WD,Normal

In [41]:
# ten_rows.to_csv("ten_rows.csv", index=False)

In [42]:
three_rows = test.iloc[45:48, :].copy()
three_rows

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
45,1506,20,RL,NaN,10456,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
46,1507,60,RL,80.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,WD,Normal
47,1508,50,RL,NaN,18837,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal

In [43]:
# three_rows.to_csv("three_rows.csv", index=False)

In [50]:
ddd = pd.read_csv("one_row.csv")
ddd

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1506,20,RL,NaN,10456,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal